# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function to strip Byte Order Marks (BOM) out of JSON data that is returned from some online API calls.
#'
#' @param df The API response to remove BOMs from.
#' @export
tidy_bom <- function(df) {
    .Call(emisc_tidy_bom, df)
}

