# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function for \code{\link{strip_bom}}
#'
#' @param df The API response to remove BOMs from.
#' @export
tidy_bom <- function(df) {
    .Call(`_emisc_tidy_bom`, df)
}

